cors:
  originPatterns: http://localhost:8080
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/restapi?useTimezone=true&serverTimezone=UTC
    username: root
    password: root123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    #    properties:
    #      hibernate:
    #        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
spring-doc:
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true
